name: Documentation Quality

on:
  pull_request:

jobs:
  vale:
    name: Vale Documentation Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Vale
        uses: errata-ai/vale-action@v2.1.1
        with:
          files: src/
